from .remove_inlined_style import RemoveInlinedStyle
from .add_atom_feed import AddAtomFeed
from .add_file_icons import AddFileIcons
from .add_breadcrumb import AddBreadcrumb
from .add_patreon_button import AddPatreonButton
from .add_twitter_card import AddTwitterCard
from .fix_notion_links import FixNotionLinks
from .fix_youtube_embeds import FixYoutubeEmbeds
from .add_analytics_tag import AddAnalyticsTag
from .generate_thumbnails import GenerateThumbnails
from .add_favicon import AddFavicon
from .postprocess_inlined_styles import PostprocessInlinedStyles
from .postprocess_changelog import PostprocessChangelog
from .postprocess_index import PostprocessIndex